# application-prod.properties
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=2
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
server.port=${PORT:8080}
spring.mail.username=${EMAIL_USERNAME:samlol25d@gmail.com}
spring.mail.password=${EMAIL_PASSWORD:olenomemes123}